const openai = require("../config/openai");

exports.generate = async (requestData) => {
  const { topic, level, difficulty, type, language } = requestData;

  // Check if OpenAI API key is properly set
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === 'your_openai_api_key_here' || process.env.OPENAI_API_KEY === 'sk-your-actual-openai-api-key') {
    // Return mock content for testing
    return {
      title: `${topic} - Generated Content`,
      level,
      difficulty,
      type,
      language,
      content: `This is a sample ${type} about ${topic} at ${level} level. This content is generated for testing purposes. In a real scenario, this would be generated by OpenAI's GPT model with rich, educational content tailored to your language learning needs.`
    };
  }

  const prompt = `
Generate a ${type} about "${topic}".
Level: ${level}
Difficulty: ${difficulty}
Language: ${language}
Make it educational, clear, and concise.
`;

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: "You are an educational content generator." },
      { role: "user", content: prompt }
    ],
    temperature: 0.7
  });

  return {
    title: `${topic} - Generated Content`,
    level,
    difficulty,
    type,
    language,
    content: response.choices[0].message.content
  };
};
